package com.nsoz.constants;

public interface SkillName {
    public static final int CHIEU_CO_BAN = 0; // Kiếm gỗ
    public static final int CHIEU_HIYOKO = 1; // Kiếm 10
    public static final int CHIEU_AMAGEDON = 2; // Kiếm 15
    public static final int CHIEU_JIZOKUZAN = 3; // Kiếm 20
    public static final int CHIEU_KAKYUU = 4; // Kiếm 25
    public static final int CHIEU_X_ZANGEKI = 5; // Kiếm 30
    public static final int CHIEU_RAIKOU = 6; // Kiếm 35
    public static final int CHIEU_HIHEBUN = 7; // Kiếm 40
    public static final int CHIEU_SHUURAI = 8; // Kiếm 45
    public static final int CHIEU_CHOUKOUHIRENZO = 9; // Kiếm 50
    public static final int CHIEU_PAWARAIKOU = 55; // Kiếm 60
    public static final int CHIEU_MAAJIZANGEKI = 61; // Kiếm 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_1 = 67; // Phân thân kiếm
    public static final int CHIEU_IKKAKUJUU = 73; // Kiếm 80
    public static final int CHIEU_ENKO_BAKUSATSU = 79; // Kiếm 100
    public static final int CHIEU_KIEM = 85; // Kiếm 120
    public static final int CHIEU_OTAMA = 10; // Tiêu 10
    public static final int CHIEU_ITOTAMA = 11; // Tiêu 15
    public static final int CHIEU_KASOUSHURIKEN = 12; // Tiêu 20
    public static final int CHIEU_TAIYOUTAMA = 13; // Tiêu 25
    public static final int CHIEU_BIKOUSHURIKEN = 14; // Tiêu 30
    public static final int CHIEU_HOSHITAMA = 15; // Tiêu 35
    public static final int CHIEU_HINOTAMA = 16; // Tiêu 40
    public static final int CHIEU_HIJOUKAI = 17; // Tiêu 45
    public static final int CHIEU_CHOUKOU_SHURIKEN = 18; // Tiêu 50
    public static final int CHIEU_TOTOGAI = 56; // Tiêu 60
    public static final int CHIEU_BAANINGUFUKIYA = 62; // Tiêu 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_2 = 68; // Phân thân tiêu
    public static final int CHIEU_HIBASHIRI = 78; // Tiêu 80
    public static final int CHIEU_TSUMABENI = 83; // Tiêu 100
    public static final int CHIEU_TIEU = 86; // Tiêu 120
    public static final int CHIEU_YOKOBATAN = 19; // Kunai 10
    public static final int CHIEU_AKAIAME = 20; // Kunai 15
    public static final int CHIEU_MIZUIBATAN = 21; // Kunai 20
    public static final int CHIEU_AOIAME = 22; // Kunai 25
    public static final int CHIEU_UZUBATAN = 23; // Kunai 30
    public static final int CHIEU_HIBIKOU = 24; // Kunai 35
    public static final int CHIEU_KOGOERU = 25; // Kunai 40
    public static final int CHIEU_JOTENTE = 26; // Kunai 45
    public static final int CHIEU_CHOUKOUKOGO = 27; // Kunai 50
    public static final int CHIEU_KITSUKEMAGUMA = 57; // Kunai 60
    public static final int CHIEU_FURIIZUKATTO = 63; // Kunai 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_3 = 69; // Phân thân kunai
    public static final int CHIEU_SAIHYOKEN = 75; // Kunai 80
    public static final int CHIEU_SHABONDAMA = 81; // Kunai 100
    public static final int CHIEU_KUNAI = 87; // Kunai 120
    public static final int CHIEU_UZUSA = 28; // Cung 10
    public static final int CHIEU_WASHIHITOMI = 29; // Cung 15
    public static final int CHIEU_KINKINSA = 30; // Cung 20
    public static final int CHIEU_SOGEKIHEI = 31; // Cung 25
    public static final int CHIEU_NIKINKINSA = 32; // Cung 30
    public static final int CHIEU_JOUTENHITOMI = 33; // Cung 35
    public static final int CHIEU_KOGOSA = 34; // Cung 40
    public static final int CHIEU_KYSHOUMA = 35; // Cung 45
    public static final int CHIEU_CHOUSOUKINKINSA = 36; // Cung 50
    public static final int CHIEU_TOTAAIGO = 58; // Cung 60
    public static final int CHIEU_FUROOZUNKYUUSEN = 64; // Cung 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_4 = 70; // Phân thân cung
    public static final int CHIEU_AISU_MEIKU = 76; // Cung 80
    public static final int CHIEU_KOGORASERU = 82; // Cung 100
    public static final int CHIEU_CUNG = 88; // Cung 120
    public static final int CHIEU_ENCHOKUTO = 37; // Đao 10
    public static final int CHIEU_KONOITOAME = 38; // Đao 15
    public static final int CHIEU_MAROYAKATO = 39; // Đao 20
    public static final int CHIEU_MAGUMANDARI = 40; // Đao 25
    public static final int CHIEU_CHOUSOUTO = 41; // Đao 30
    public static final int CHIEU_AISUBAAGU = 42; // Đao 35
    public static final int CHIEU_HAYATETO = 43; // Đao 40
    public static final int CHIEU_ZENPANTEKI = 44; // Đao 45
    public static final int CHIEU_RAIKOUTO = 45; // Đao 50
    public static final int CHIEU_IKENNOTTO = 59; // Đao 60
    public static final int CHIEU_BAASUTOSUTOOMU = 65; // Đao 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_5 = 71; // Phân thân đao
    public static final int CHIEU_KAMINARI = 74; // Đao 80
    public static final int CHIEU_RAIJIN = 80; // Đao 100
    public static final int CHIEU_DAO = 89; // Đao 120
    public static final int CHIEU_OUCHIA = 46; // Quạt 10
    public static final int CHIEU_SUISHOU = 47; // Quạt 15
    public static final int CHIEU_OOUCHIA = 48; // Quạt 20
    public static final int CHIEU_KUSENMONO = 49; // Quạt 25
    public static final int CHIEU_BAKKUUCHIHA = 50; // Quạt 30
    public static final int CHIEU_HAYATEMI = 51; // Quạt 35
    public static final int CHIEU_BOUSOUHAYATE = 52; // Quạt 40
    public static final int CHIEU_TORUNEEDO = 53; // Quạt 45
    public static final int CHIEU_TATSUMAKI = 54; // Quạt 50
    public static final int CHIEU_OOENJO = 60; // Quạt 60
    public static final int CHIEU_KOUGEKITENRAI = 66; // Quạt 70
    public static final int NHAN_THUAT_KAGE_BUNSHIN_6 = 72; // Phân thân quạt
    public static final int CHIEU_KOKAZE = 77; // Quạt 80
    public static final int CHIEU_KAMIKAZE = 84; // Quạt 100
    public static final int CHIEU_QUAT = 90; // Quạt 120
}
